language: java
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk9
os:
  - linux

#cache:
  #directories:
  #- $HOME/.m2/

#script: "mvn cobertura:cobertura"

#after_success:
  #- bash <(curl -s https://codecov.io/bash)